// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi00rBkXMwQhs1E9v1yDlFvH3Ftp4lvdo',
    appId: '1:66485528415:web:90787e21e3f0fb014ff8ea',
    messagingSenderId: '66485528415',
    projectId: 'budgetbook-2d6ee',
    authDomain: 'budgetbook-2d6ee.firebaseapp.com',
    storageBucket: 'budgetbook-2d6ee.firebasestorage.app',
    measurementId: 'G-P1FN7LE33S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyyg3QU1ZlG-P41KF1DXxz9yfskeuNNI',
    appId: '1:66485528415:android:ffd359848623bee84ff8ea',
    messagingSenderId: '66485528415',
    projectId: 'budgetbook-2d6ee',
    storageBucket: 'budgetbook-2d6ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsLnv3HbY05dtCeA3loDpJTCX9boz48g',
    appId: '1:66485528415:ios:57d0ad4d49d078d24ff8ea',
    messagingSenderId: '66485528415',
    projectId: 'budgetbook-2d6ee',
    storageBucket: 'budgetbook-2d6ee.firebasestorage.app',
    iosBundleId: 'com.example.mobileproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsLnv3HbY05dtCeA3loDpJTCX9boz48g',
    appId: '1:66485528415:ios:57d0ad4d49d078d24ff8ea',
    messagingSenderId: '66485528415',
    projectId: 'budgetbook-2d6ee',
    storageBucket: 'budgetbook-2d6ee.firebasestorage.app',
    iosBundleId: 'com.example.mobileproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi00rBkXMwQhs1E9v1yDlFvH3Ftp4lvdo',
    appId: '1:66485528415:web:27a7b8e6000910e64ff8ea',
    messagingSenderId: '66485528415',
    projectId: 'budgetbook-2d6ee',
    authDomain: 'budgetbook-2d6ee.firebaseapp.com',
    storageBucket: 'budgetbook-2d6ee.firebasestorage.app',
    measurementId: 'G-49G0P31LRQ',
  );
}
